apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: refreshTokens
spec:
  database: {{ .Values.psql.name }}
  name: refreshTokens
  schema:
    postgres:

      primaryKey:
        - id

      foreignKeys:
      - columns:
          - publicAddress
        references:
          table: users
          columns:
            - publicAddress

      indexes:
        - columns: 
          - id
          isUnique: true

      columns:

      - name: id
        type: uuid
        constraints:
          notNull: true
      
      # User's public Address
      - name: publicAddress
        type: varchar
        constraints:
          notNull: true
      
      - name: token
        type: varchar
        constraints:
          notNull: true

      # Record Created At
      - name: revoked
        type: boolean
        constraints:
          notNull: true

