apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: users
spec:
  database: {{ .Values.psql.name }}
  name: users
  schema:
    postgres:

      primaryKey:
      - publicAddress

      indexes:
        - columns: [publicAddress]
          isUnique: true

      columns:

      # User's public Address
      - name: publicAddress
        type: text
        constraints:
          notNull: true
      
      - name: username
        type: text
        constraints:
          notNull: true

      # Record Created At
      - name: nonce
        type: timestamp
        constraints:
          notNull: true

