apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: refresh-tokens
spec:
  database: {{ .Values.psql.name }}
  name: refresh_tokens
  schema:
    postgres:

      primaryKey:
        - id

      foreignKeys:
      - columns:
          - address
        references:
          table: users
          columns:
            - address

      columns:

      - name: id
        type: uuid
        constraints:
          notNull: true
      
      # User's public Address
      - name: address
        type: text
        constraints:
          notNull: true
      
      - name: token
        type: text
        constraints:
          notNull: true

      # Record Created At
      - name: revoked
        type: boolean
        constraints:
          notNull: true

